#!/usr/bin/env python3
"""Generate reviewable plan views and publication material from tasks.json.

This writes local files only. The JSON export is portable review/import material,
not an invented Tanduna API request or evidence of native publication.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def joined(values):
    return ', '.join(values) or 'none'


def generated_files(plan):
    tasks = plan['tasks']
    by_id = {task['id']: task for task in tasks}
    counts = Counter(task['targetRelease'] for task in tasks)
    states = Counter(task['status'] for task in tasks)
    preface = (
        '<!-- Generated by python3 tools/render_plan.py from plan/tasks.json. Do not edit this view. -->\n\n'
        'Task status is canonical in [plan/tasks.json](plan/tasks.json); [STATUS.md](STATUS.md) '
        'records the current narrative and evidence. Planning completion is separate from implementation, '
        'automated results, runtime proof, human review and public release.\n\n'
        f'This programme contains **{len(tasks)} current task rows in {len(plan["waves"])} waves**, '
        f'including **{counts["0.1"]} narrow 0.1 outcomes**. The exact 27 historical source objects '
        '(three DONE documentation/tooling foundations and 24 PLANNED scientific/build contracts) '
        'remain unchanged in [immutable lineage](plan/lineage/manifest.json). '
        'New outcomes do not retroactively complete the original contracts.\n\n'
    )
    roadmap = ['# Research Continuum roadmap\n\n', preface, '## Objective and limits\n\n', plan['objective'] + '\n\n']
    roadmap += ['- ' + value + '\n' for value in plan['limits']]
    roadmap += ['\nRelease horizons express scope, not dates or approved hardware/spend. Later outcomes require '
                'their own accepted wave evidence, rights and resources. The historical training-first '
                'programme remains retained; the owner separately authorizes the narrow numerical 0.1 path.\n\n',
                '## Scope and current evidence\n\n', '| Horizon | Rows |\n| --- | ---: |\n']
    roadmap += [f'| {key} | {value} |\n' for key, value in counts.items()]
    roadmap += ['\nCurrent row states: ' + '; '.join(f'{key}: {value}' for key, value in states.items()) + '.\n\n',
                '## Execution and replanning\n\n',
                'For an immediate task, the owner binds actual files, available commands, falsifiers and '
                'exit evidence in a bounded execution packet before implementation. Capacity, rights, '
                'environment and qualified-review gates are checked at entry. Cut extra objectives, rich UI, '
                'agent search and remote workers before real computation, reserved evidence, recovery or '
                'complete reporting. Replan at an observed failure or accepted wave gate; retain all negative results.\n\n',
                '## Outcome waves\n\n']
    for wave in plan['waves']:
        roadmap += [f'### {wave["id"]}: {wave["title"]}\n\n',
                    f'Outcome: {wave["outcome"]}\n\n',
                    f'Horizon: **{wave["targetRelease"]}**. Entry dependencies: {joined(wave["entryDependencies"])}. '
                    f'Assigned rows: {len(wave["taskIds"])}.\n\n']
        for identifier in wave['taskIds']:
            task = by_id[identifier]
            roadmap += [f'- **{identifier} — {task["title"]}** ({task["status"]}).\n']
        roadmap += [f'\nExit evidence: {wave["exitEvidence"]}\n\n',
                    'Gate decision: continue only with the required observed evidence and authority; otherwise repair, descope or hold.\n\n']
    roadmap += ['## Historical source reconciliation\n\n',
                'The [full generated task contracts](TASKS.md) and [publication export](plan/exports/tanduna-plan.json) '
                'carry original acceptance, structured prerequisites, textual-only prerequisite evidence and successor IDs. '
                'Original wave text and gates are preserved byte-for-byte in both historical snapshots. '
                'A prerequisite successor mapping proves traceability; it does not declare the original prerequisite satisfied.\n\n',
                '| Original | Historical state | Treatment | Current successor count | Narrow 0.1 successors |\n| --- | --- | --- | ---: | ---: |\n']
    for mapping in plan['sourceMappings']:
        roadmap += [f'| {mapping["sourceId"]} | {mapping["originalStatus"]} | {mapping["treatment"]} | '
                    f'{len(mapping["successorIds"])} | {len(mapping["narrowSuccessorIds"])} |\n']
    publication = plan['publication']
    access = publication['releaseAccess']
    roadmap += ['\n## Publication and access\n\n',
                f'Native publication evidence: **{publication["status"]}**. The live observation at '
                f'{publication["observedAt"]} found {publication["observedNativeTaskCount"]} native tasks and '
                f'“{publication["observedNativePlan"]}”. The recorded proposal is {publication["proposalState"]}.\n\n',
                f'0.1 access: **{access["status"]}**. {access["instructions"]}\n\n']
    if access['url']:
        roadmap += [f'Public artifact: [{access["version"]}]({access["url"]}).\n\n']
    roadmap += [f'[Public roadmap]({publication["roadmapUrl"]}) · [Public tasks]({publication["tasksUrl"]})\n\n',
                'Local exports, draft task IDs and submitted-but-unaccepted proposals do not satisfy native publication. '
                'Use supported review/approval controls, then read back actual public counts, dependency links, scope and access instructions.\n']

    contracts = ['# Research Continuum task contracts\n\n', preface,
                 'Every row below is a bounded outcome contract. `evidenceRefs` must identify actual evidence '
                 'before a new task advances beyond PLANNED. Human and public-release evidence remain distinct; '
                 'DONE is reserved for the three retained historical foundation rows.\n\n']
    for task in tasks:
        contracts += [f'## {task["id"]} — {task["title"]}\n\n',
                      f'- Outcome: {task["outcome"]}\n',
                      f'- Area: {task["featureArea"]}; wave: RC-W{task["wave"]:02d}; release horizon: {task["targetRelease"]}.\n',
                      f'- Status: **{task["status"]}**; basis: {task["basis"]}.\n',
                      f'- Prerequisites: {joined(task["dependsOn"])}.\n',
                      f'- Acceptance: {task["acceptance"]}\n',
                      f'- Source contracts: {joined(task["sourceRefs"])}; decisions: {joined(task["decisionRefs"])}.\n',
                      f'- Risk and evidence needs: {task["riskEvidenceNeeds"]}\n',
                      f'- Recorded evidence: {joined(task["evidenceRefs"])}.\n',
                      f'- Native platform ID: {task["platformId"] or "not assigned"}.\n\n']
        for dependency, reason in task['dependencyRationale'].items():
            contracts += [f'Prerequisite {dependency}: {reason}\n\n']
    contracts += ['## Immutable source contracts and mapping\n\n']
    for mapping in plan['sourceMappings']:
        contracts += [f'### {mapping["sourceKey"]}\n\n',
                      f'- Revision: {mapping["sourceRevision"]}; original state: **{mapping["originalStatus"]}**.\n',
                      f'- Original acceptance: {mapping["originalAcceptance"]}\n',
                      f'- Structured prerequisites: {joined(mapping["structuredPrerequisites"])}.\n',
                      f'- Additional textual task-ID prerequisites: {joined(mapping["textualPrerequisites"])}. {mapping["textualPrerequisiteEvidence"]}\n',
                      f'- Frozen predecessor: {mapping["frozenPredecessor"] or "none stated"}; original native ID: {mapping["sourcePlatformId"] or "none recorded"}.\n',
                      f'- Treatment: {mapping["treatment"]}. {mapping["reason"]}\n',
                      f'- Successors: {joined(mapping["successorIds"])}.\n',
                      f'- Narrow 0.1 only: {joined(mapping["narrowSuccessorIds"])}.\n',
                      f'- Prerequisite coverage: {mapping["prerequisiteCoverage"]}\n\n']
    contracts += ['Source/decision locators:\n\n']
    for source in plan['sourceRecords']:
        contracts += [f'- {source["id"]}: [{source["kind"]}]({source["locator"]}) — {source["description"]}\n']

    exported = {
        'format': 'research-continuum-native-plan-review-v1',
        'notice': 'Review/import material only. Not a platform API request, publication approval or completion claim.',
        'project': plan['project'], 'projectId': publication['projectId'],
        'contractVersion': plan['contractVersion'], 'objective': plan['objective'], 'limits': plan['limits'],
        'taskCount': len(tasks), 'waveCount': len(plan['waves']), 'horizonCounts': dict(counts),
        'waves': plan['waves'], 'tasks': tasks, 'sourceMappings': plan['sourceMappings'],
        'publication': publication, 'planningDecisions': plan['planningDecisions'],
    }
    output = io.StringIO(newline='')
    columns = ['id', 'title', 'outcome', 'featureArea', 'wave', 'targetRelease', 'dependsOn', 'acceptance',
               'sourceRefs', 'decisionRefs', 'riskEvidenceNeeds', 'status', 'evidenceRefs', 'platformId']
    writer = csv.DictWriter(output, fieldnames=columns, lineterminator='\n')
    writer.writeheader()
    for task in tasks:
        writer.writerow({key: json.dumps(task[key], ensure_ascii=False) if isinstance(task[key], (list, dict)) else task[key] for key in columns})
    return {
        'ROADMAP.md': ''.join(roadmap), 'TASKS.md': ''.join(contracts),
        'plan/exports/tanduna-plan.json': json.dumps(exported, indent=2, ensure_ascii=False) + '\n',
        'plan/exports/tasks.csv': output.getvalue(),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if generated views or exports are stale')
    args = parser.parse_args()
    plan = json.loads((ROOT / 'plan/tasks.json').read_text(encoding='utf-8'))
    stale = []
    for relative, content in generated_files(plan).items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    if stale:
        print('FAIL: stale generated files: ' + ', '.join(stale))
        return 1
    print('PASS: generated plan views and publication exports ' + ('match canonical state' if args.check else 'written locally'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
